# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.3.4-node-browsers
         env:
           PGHOST: 127.0.0.1
           PGUSER: total_transport_test
           RAILS_ENV: test
       - image: circleci/postgres:9.4.12-alpine
         env:
           POSTGRES_USER: total_transport_test
           POSTGRES_DB: total_transport_test
           POSTGRES_PASSWORD: ""
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
    
    working_directory: ~/repo

    steps:
      - run:
          name: install system level dependencies
          command: |
            sudo apt-get update -y; true
            sudo apt-get install qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x postgresql-client google-chrome-stable
      
      - run:
          name: Install Chrome
          command: |
            sudo apt-get update
            sudo apt-get install libappindicator3-1
            curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome.deb
            sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
            rm google-chrome.deb
      
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
        
      # Database setup
      - run: bundle exec rake db:migrate

      # run tests!
      - run:
          name: run tests
          command: bundle exec rake && bundle exec brakeman -z -q
